name: Validate terraform fmt & validate

on:
  pull_request:
    branches: [main, master]

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    name: terraform fmt check
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: Run terraform fmt
        run: terraform fmt -check -recursive

      - name: Run terraform validate
        run: terraform validate
